services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

    ports:
    - 27018:27017
    volumes:
    - mongodb_data_container:/data/db

    networks:
    - TaxaNet

  BookingService:
    image: mortenlundmikkelsen/bookingservice:latest
    environment:
      - rabbitmqHost=dev-rabbit
      - PlanPath=//srv/plans
      - connectionString=mongodb://admin:1234@mongodb-dev:27017
      - databaseName=TaxaDB
      - collectionName=users
   
    ports:
    - 5001:80
    volumes:
    - mongodb_data_container:/data/db

    networks:
    - TaxaNet
volumes:
  mongodb_data_container:
  images_data:
    external: false

networks:
  TaxaNet:
    driver: bridge
