services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

    ports:
    - 27018:27017
    volumes:
    - mongodb_data_container:/data/db

    networks:
    - TaxaNet
    
volumes:
  mongodb_data_container:
  images_data:
    external: false

networks:
  TaxaNet:
    driver: bridge
